name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  vader-tests:
    name: Vader tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [true] # only test on neovim currently
        version: [nightly, v0.4.3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: vader.vim
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - uses: actions/setup-python@v1
      - name: Install nvr
        run: |
          pip install neovim-remote
          nvr --version
      - name: Run vader tests
        env:
          VIM_EXEC: ${{ steps.vim.outputs.executable }}
        run: |
          $VIM_EXEC --version
          $VIM_EXEC -u test/vimrc -c 'Vader! test/test_cmdline.vader'


  vint:
    name: Run vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install vim-vint
      - run: vint --error --verbose --enable-neovim --color --style ./autoload ./plugin
